HELP = 'help'
LIST_EXPENSE = 'list_expense'
SETTLE_EXPENESE = 'settle_expense'
CREATE_EXPENSE = 'create_expense'
GET_NOTIFICATIONS = 'get_notifications'
START = 'start'
CONNECT = 'connect'
CANCEL = 'cancel'
